### ISSUE TITLE
Export custom `ClusterRole`s and `SecurityContextConstraint`s

### ISSUE THREAD

**Issue by dmartinol** [RHEcosystemAppEng/SaaSi#10]
When the original environment creates new `ClusterRole`s or `SecurityContextConstraint`s, the same must be identified by the install-builder application and exported to replicate the same RBAC settings on the target environment.

- To identify that a `ClusterRole`s or `SecurityContextConstraint`s is needed, we use the `ServiceAccount` in the current namespace and verify whether a `RoleBinding` or `ClusterRoleBinding` is mapping the given `ServiceAccount` to a `ClusterRole`
- In alternative, the `ServiceAccount` can be modelled as one of the entries in the `users` field of a `SecurityContextConstraint`
  - In this case, the recommended approach is to create a new `SecurityContextConstraint` on the target environment and link it to the `ServiceAccount` using a regular `ClusterRoleBinding`

**Comment by zvigrinberg** [comment]
Adding Another Possible Scenario that should be checked in the process of exporting  the RBAC manifests:
-  For any namespace involved in the source cluster, we need also to Identify  If There is a `Role` , that permits to use a `SecurityContextConstraint`, and is mapped to a `ServiceAccount` using a `RoleBinding` object.

Example for such Scenario:
```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: use-anyuid-scc
rules:
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    resourceNames: ["anyuid"]
    verbs: ["use"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: use-anyuid-scc
subjects:
  - kind: ServiceAccount
    name: my-serviceaccount
roleRef:
  kind: Role
  name: use-anyuid-scc
  apiGroup: rbac.authorization.k8s.io
```

We should also have to make sure that this work will be done only for serviceaccounts that attached to pods(if deployment/statefulset/job don't have service account name explicitly specified, then we can infer that default `ServiceAccount` is being used for the running pod).
