### ISSUE TITLE
Cleanup unneeded/harmful configurations in exported resources

### ISSUE THREAD

**Issue by dmartinol** [RHEcosystemAppEng/SaaSi#17]
- Either with specific code or with `crane` plugin
- `ServiceAccount` resources are affected, need to validate other kinds as well

Example of configured resource:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  holdings
  namespace: holdings
  labels:
    infinitySubChart: "true"
```
The same resource once exported:
```yaml
apiVersion: v1
imagePullSecrets:
- name: holdings-dockercfg-5kzxh
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: infinity-msuat
    meta.helm.sh/release-namespace: helm-releases
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: Helm
    infinitySubChart: "true"
  name: holdings
secrets:
- name: holdings-token-986hz
- name: holdings-dockercfg-5kzxh
```
