### ISSUE TITLE
Integrate the infrastructure exporter and deployer

### ISSUE THREAD

**Issue by dmartinol** [RHEcosystemAppEng/SaaSi#28]
The `exporter` application receives input data about the location and authentication to the source cluster, like:
```yaml
cluster:
  server: API-SERVER-URL
  user: USERNAME
  token: TOKEN
```

The `deployer` application can either receive the same configuration, e.g.:
```yaml
cluster:
  server: API-SERVER-URL
  user: USERNAME
  token: TOKEN
```
or run one of the clusters deployed by the `deployer`, identified by a userName:
```yaml
cluster:
  userName: CUSTOM_CLUSTER_NAME
```
