### ISSUE TITLE
Define app-deployer

### ISSUE THREAD

**Issue by dmartinol** [RHEcosystemAppEng/SaaSi#60]
- Isolate the code to deploy the app configuration and generate the app-deployer image from it.
- The application exposes 2 runtime modes:
- `service`: exposing async REST POST services to trigger the export (e.g. /deploy) with configuration provided in the data payload
- `CLI`: as a CLI tool with given flags (e.g. `--as-cli` and `--filename`)
- In both cases, the input configuration defines the minimum set of parameters like:
```yaml
application:
  name: APP
  namespaceMappingFormat: "%s-prod"
  namespaces:
  - name: NS1
    # If missing, the namespaceMappingFormat or the original name are applied
    target: NEW-NS1
    params:
    - configMap: MAP-1
    - ...
```
- In case of `service` mode, the async REST call also takes an extra input to identify the REST path to be invoked to notify about the completion (REST POST is used)
- In both cases, the output is a JSON document reporting the minimum data:
```json
{
  "deploymentId": "new UUID or defined in the input"
  "applicationName": "APP"
  "status": "ok/failed (use HTTP status code?)"
  "errorMessage": "optional"
  "location": "relative path to app manifests/kustomize configuration"
}
```
- Includes GitHub action to trigger the image build and push it on Quay.io
- Exported folders and output folders are stored in well defined locations
  - For `service` mode, under a volume mounted at startup time and defined by env variables (e.g., `EXPORT_PATH` and `OUTPUT_PATH`)
  - For `CLI` mode, under paths defined by runtime options (e.g. `--export-path` and `--output-path`)
- Document error handling and execution examples
- As agreed, the initial implementation can use the CLI tools to run the actual export (e.g., kustomize), then we can move to a programmatic implementation or create a new issue for the leftover
