### ISSUE TITLE
Define infra-deployer

### ISSUE THREAD

**Issue by dmartinol** [RHEcosystemAppEng/SaaSi#61]
- Isolate the code to deploy the infrastructure and generate the infra-deployer image from it.
- The application exposes 2 runtime modes:
- `service`: exposing async REST POST services to trigger the export (e.g. /deploy) with configuration provided in the data payload
- `CLI`: as a CLI tool with given flags (e.g. `--as-cli` and `--filename`)
- In both cases, the input configuration defines the minimum set of parameters like:
```yaml
cluster:
  fromClusterId: CLUSTER_ID_OF_SOURCE_CLUSTER
  clusterId: DEPLOYED_CLUSTER_ID
  aws:
    aws_public_domain: <PUBLIC_DOMAIN_ROUTE53_SERVICE>
    aws_account_name: <ACCOUNT_NAME>
    aws_access_key_id: <SA_ACCESS_KEY>
    aws_secret_access_key: <SA_SECRET_ACCESS_KEY>
  params:
    CLUSTER_NAME: ABCDEFG
    CLUSTER_BASE_DOMAIN: ABCDEFG
    WORKER_COUNT: NNN
```
- In case of `service` mode, the async REST call also takes an extra input to identify the REST path to be invoked to notify about the completion (REST POST is used)
- In both cases, the output is a JSON document reporting the minimum data:
```json
{
  "deploymentId": "new UUID or defined in the input"
  "clusterId": "same as input"
  "status": "ok/failed (use HTTP status code?)"
  "errorMessage": "optional"
  "location": "relative path to new cluster configurations (e.g. kubeconfig)"
}
```
- Includes GitHub action to trigger the image build and push it on Quay.io
- Exported folders and output folders are stored in well defined locations
  - For `service` mode, under a volume mounted at startup time and defined by env variables (e.g., `EXPORT_PATH` and `OUTPUT_PATH`)
  - For `CLI` mode, under paths defined by runtime options (e.g. `--export-path` and `--output-path`)
- Document error handling and execution examples
- As agreed, the initial implementation can use the CLI tools to run the actual export (e.g., Ansible), then we can move to a programmatic implementation or create a new issue for the leftover
