### ISSUE TITLE
Filter out automatically created resources

### ISSUE THREAD

**Issue by dmartinol** [RHEcosystemAppEng/SaaSi#8]
Some resources, like ResourceBindings, might be automatically created by a controller.
We should find a way to avoid extracting them.
Example:
```yaml
apiVersion: authorization.openshift.io/v1
groupNames: null
kind: RoleBinding
metadata:
  annotations:
    openshift.io/description: Allows deploymentconfigs in this namespace to rollout
      pods in this namespace.  It is auto-managed by a controller; remove subjects
      to disable.
```
